logs_dir: logs
is_train: true
name: full_dataset_with_pretrained_6views_try7
device: cuda:0
batch_size: 8
n_epochs: 200
append_loss_every: 50
print_every: 150
#print_every: 10
validate_every: 4349
save_every: 500
save_every_nepochs: 10
start_epoch: 57
start_iteration: 253149
#start_iteration: 0
visualize_every: 1000

model:
  lr: 0.0001
  criterion: DICE_BCE #BCE | DICE | DICE_BCE
  pos_weight: 1.8 # weight of positive class
  fusion: AVG #AVG | TRANSFORMER

  encoder:
    patch_size: 16
    sequence_length: 196
    embedding_dim: 768
    patch_padding: 3

  transformer_encoder:
    d_model: 768
    nhead: 12
    num_layers: 12

  transformer_decoder:
    d_model: 768
    nhead: 12
    num_layers: 8
    num_pos_embeddings: 64

  fusion_decoder:
    d_model: 768
    nhead: 6
    num_layers: 2
    
    
evaluation:
   #ckpt_path: logs/final_models/avg_fusion/checkpoints/epoch-latest.ckpt
   ckpt_path: logs/full_dataset_with_pretrained_6views_try7/checkpoints/epoch-latest.ckpt
   #ckpt_path: logs/final_models/transformer_fusion/fusion_transformer_all_ds/checkpoints/epoch-latest.ckpt
#ckpt_path: logs/final_models/avg_fusion/epoch-50.ckpt
