logs_dir: logs
is_train: true
name: trainingV10
device: cuda:0
batch_size: 8
n_epochs: 100
print_every: 20
validate_every: 30
save_every: 50
save_every_nepochs: 10

model:
  lr: 0.0001
  criterion: BCE #BCE | BCE_LOGITS | WEIGHTED_BCE_LOGITS
  pos_weight: 1.3 # Only used if the loss value is WEIGHTED_BCE_LOGITS - weight of positive class

  encoder:
    patch_size: 13
    sequence_length: 100
    embedding_dim: 768
    patch_padding: 3

  transformer_encoder:
    d_model: 768
    nhead: 12
    num_layers: 12

  transformer_decoder:
    d_model: 768
    nhead: 12
    num_layers: 8
    num_pos_embeddings: 64
