logs_dir: logs
is_train: true
name: merge
device: cuda:0
batch_size: 8
n_epochs: 100
append_loss_every: 50
print_every: 150
validate_every: 4349
save_every: 1000
save_every_nepochs: 10
start_epoch: 0
start_iteration: 0
visualize_every: 1000



model:
  lr: 0.0001
  criterion: BCE #BCE | BCE_LOGITS | WEIGHTED_BCE_LOGITS | DICEANDBCE
  pos_weight: 1.8 # Only used if the loss value is WEIGHTED_BCE_LOGITS - weight of positive class

  encoder:
    patch_size: 16
    sequence_length: 196
    embedding_dim: 768
    patch_padding: 3

  transformer_encoder:
    d_model: 768
    nhead: 12
    num_layers: 12

  transformer_decoder:
    d_model: 768
    nhead: 12
    num_layers: 8
    num_pos_embeddings: 64
